# Generated by Django 5.2.5 on 2025-08-13 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_jobapplication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="application_deadline",
            field=models.DateTimeField(
                blank=True, help_text="Application deadline", null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this job is actively accepting applications",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_currency",
            field=models.CharField(
                default="USD", help_text="Currency code (USD, EUR, etc.)", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum salary in local currency",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum salary in local currency",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="EmployerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("company_description", models.TextField()),
                ("company_website", models.URLField(blank=True)),
                (
                    "company_logo",
                    models.ImageField(blank=True, upload_to="company_logos/"),
                ),
                (
                    "company_size",
                    models.CharField(
                        choices=[
                            ("1-10", "1-10 employees"),
                            ("11-50", "11-50 employees"),
                            ("51-200", "51-200 employees"),
                            ("201-500", "201-500 employees"),
                            ("501-1000", "501-1000 employees"),
                            ("1000+", "1000+ employees"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("address_line1", models.CharField(max_length=200)),
                ("address_line2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state_province", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="United States", max_length=100)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the employer has been verified",
                    ),
                ),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this saved search", max_length=100
                    ),
                ),
                ("query", models.CharField(blank=True, max_length=200)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("job_type", models.CharField(blank=True, max_length=50)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_remote", models.BooleanField(blank=True, null=True)),
                (
                    "date_posted",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Any time"),
                            ("1", "Past 24 hours"),
                            ("3", "Past 3 days"),
                            ("7", "Past week"),
                            ("14", "Past 2 weeks"),
                            ("30", "Past month"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "email_alerts",
                    models.BooleanField(
                        default=False,
                        help_text="Send email alerts for new jobs matching this search",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "name")},
            },
        ),
    ]
