# Generated by Django 5.2.5 on 2025-08-13 22:53

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="My Budget", max_length=100)),
                (
                    "monthly_income",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "housing_rent_bond",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "groceries_household",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "utilities_water_electricity",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "transport_fuel_taxi",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "education_school_fees",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "healthcare_medical",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "insurance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "loan_repayments",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "family_black_tax",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "entertainment_lifestyle",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "savings_investments",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "other_expenses",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DebtAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_name", models.CharField(max_length=100)),
                (
                    "debt_type",
                    models.CharField(
                        choices=[
                            ("home_loan", "Home Loan"),
                            ("car_loan", "Car Loan"),
                            ("personal_loan", "Personal Loan"),
                            ("credit_card", "Credit Card"),
                            ("store_account", "Store Account"),
                            ("student_loan", "Student Loan"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("creditor_name", models.CharField(blank=True, max_length=100)),
                (
                    "original_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "annual_interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("50.00")),
                        ],
                    ),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("original_term_months", models.IntegerField(blank=True, null=True)),
                ("remaining_term_months", models.IntegerField(blank=True, null=True)),
                ("next_payment_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_paid_off", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debt_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-current_balance"],
            },
        ),
        migrations.CreateModel(
            name="DebtPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "interest_portion",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "principal_portion",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "balance_after_payment",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "debt_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="moneyrite.debtaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="SalaryCalculation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pay_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "pay_period",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("annually", "Annually"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "hours_per_week",
                    models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
                ),
                (
                    "gross_monthly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "gross_annual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "income_tax_monthly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "uif_monthly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "medical_tax_credit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "pension_contribution",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "net_monthly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_calculations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserFinancialProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_hours_per_week",
                    models.DecimalField(
                        decimal_places=2,
                        default=40.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("168.00")),
                        ],
                    ),
                ),
                ("include_medical_aid", models.BooleanField(default=False)),
                (
                    "medical_aid_members",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("include_pension", models.BooleanField(default=False)),
                (
                    "pension_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("27.50")),
                        ],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
